# Conda Environment für EDA 
# 
# Änderungen gegenüber Original:
# - Python 3.13 → 3.12: Bessere Paketkompatibilität
# - ydata-profiling hinzugefügt - EDA-Report 
# - Paketversionen angepasst für Kompatibilität mit Python 3.12

name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - hydra-core=1.3.2
  - matplotlib>=3.8
  - pandas>=2.2
  - pip>=24.0
  - scikit-learn>=1.5
  - jupyterlab>=4.0
  - ipywidgets>=8.0
  - pip:
      - mlflow>=2.14
      - wandb>=0.17
      - ydata-profiling>=4.8  # EDA Notebook